name: Eleventy generator action
description: A custom GitHub Action to build static sites using Eleventy.
author: 'Your Name'
runs:
  using: 'node20'
  main: 'index.js'

inputs:
  node_version:
    description: 'The version of Node.js to install.'
    required: true
    default: '23'
  working_directory:
    description: 'The working directory to use.'
    required: false
    default: '.'
  output:
    description: 'Optional: Specify the output directory for Eleventy.'
    required: false
  quiet:
    description: 'Optional: Run Eleventy in quiet mode.'
    required: false

outputs:
  build_status:
    description: 'Status of the Eleventy build.'
